-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_settings (
  key text NOT NULL,
  value boolean DEFAULT true,
  label text,
  CONSTRAINT app_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  roles ARRAY NOT NULL DEFAULT '{invitado}'::text[],
  first_name text,
  last_name text,
  national_id text,
  department text,
  job_title text,
  phone text,
  updated_at timestamp with time zone DEFAULT now(),
  plain_text_reports boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vehiculos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  codigo text NOT NULL UNIQUE,
  placa text NOT NULL,
  modelo text NOT NULL,
  año text,
  capacidad_tanque text,
  color text,
  tipo_combustible text,
  foto_url text,
  tipo text,
  current_fuel_level integer DEFAULT 100,
  last_fuel_update timestamp with time zone DEFAULT now(),
  last_oil_change_km numeric,
  last_timing_belt_km numeric,
  last_chain_kit_km numeric,
  last_wash_date timestamp with time zone,
  assigned_driver_id uuid,
  department text,
  odometro_averiado boolean DEFAULT false,
  kilometraje numeric DEFAULT 0,
  CONSTRAINT vehiculos_pkey PRIMARY KEY (id),
  CONSTRAINT vehiculos_assigned_driver_id_fkey FOREIGN KEY (assigned_driver_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.fallas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vehiculo_id uuid NOT NULL,
  reportado_por uuid,
  descripcion text NOT NULL,
  tipo_falla text NOT NULL,
  prioridad text NOT NULL DEFAULT 'Media'::text,
  estado text NOT NULL DEFAULT 'Pendiente'::text,
  fecha_solucion timestamp with time zone,
  notas_taller text,
  reported_by text,
  CONSTRAINT fallas_pkey PRIMARY KEY (id),
  CONSTRAINT fallas_vehiculo_id_fkey FOREIGN KEY (vehiculo_id) REFERENCES public.vehiculos(id)
);
CREATE TABLE public.fuel_daily_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_date date NOT NULL,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  supervisor_id uuid,
  total_liters numeric NOT NULL,
  details jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fuel_daily_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fuel_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  ticket_number text NOT NULL,
  fuel_date timestamp with time zone NOT NULL,
  vehicle_id uuid NOT NULL,
  driver_name text NOT NULL,
  liters numeric NOT NULL,
  mileage numeric NOT NULL,
  supervisor_id uuid NOT NULL,
  ticket_url text,
  notes text,
  status text DEFAULT 'active'::text,
  void_reason text,
  CONSTRAINT fuel_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fuel_logs_supervisor_id_profiles_fkey FOREIGN KEY (supervisor_id) REFERENCES public.profiles(id),
  CONSTRAINT fuel_logs_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehiculos(id)
);
CREATE TABLE public.maintenance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  vehicle_id uuid NOT NULL,
  service_type text NOT NULL,
  mileage numeric NOT NULL,
  service_date date DEFAULT CURRENT_DATE,
  performed_by text,
  notes text,
  cost numeric DEFAULT 0,
  parts_used text,
  labor_cost numeric DEFAULT 0,
  parts_cost numeric DEFAULT 0,
  CONSTRAINT maintenance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_logs_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehiculos(id)
);
CREATE TABLE public.reportes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vehiculo_id uuid NOT NULL,
  conductor text NOT NULL,
  departamento text NOT NULL,
  fecha_salida timestamp with time zone NOT NULL DEFAULT now(),
  km_salida numeric NOT NULL DEFAULT 0,
  gasolina_salida text NOT NULL,
  observaciones_salida text,
  aceite_salida boolean DEFAULT false,
  agua_salida boolean DEFAULT false,
  gato_salida boolean DEFAULT false,
  cruz_salida boolean DEFAULT false,
  triangulo_salida boolean DEFAULT false,
  caucho_salida boolean DEFAULT false,
  carpeta_salida boolean DEFAULT false,
  escalera_salida boolean DEFAULT false,
  onu_salida integer DEFAULT 0,
  ups_salida integer DEFAULT 0,
  fecha_entrada timestamp with time zone,
  km_entrada numeric,
  gasolina_entrada text,
  observaciones_entrada text,
  aceite_entrada boolean DEFAULT false,
  agua_entrada boolean DEFAULT false,
  gato_entrada boolean DEFAULT false,
  cruz_entrada boolean DEFAULT false,
  triangulo_entrada boolean DEFAULT false,
  caucho_entrada boolean DEFAULT false,
  carpeta_entrada boolean DEFAULT false,
  escalera_entrada boolean DEFAULT false,
  onu_entrada integer DEFAULT 0,
  ups_entrada integer DEFAULT 0,
  casco_salida boolean DEFAULT false,
  luces_salida boolean DEFAULT false,
  herramientas_salida boolean DEFAULT false,
  cinturones_salida boolean DEFAULT false,
  conos_salida boolean DEFAULT false,
  extintor_salida boolean DEFAULT false,
  casco_entrada boolean DEFAULT false,
  luces_entrada boolean DEFAULT false,
  herramientas_entrada boolean DEFAULT false,
  cinturones_entrada boolean DEFAULT false,
  conos_entrada boolean DEFAULT false,
  extintor_entrada boolean DEFAULT false,
  user_id uuid,
  CONSTRAINT reportes_pkey PRIMARY KEY (id),
  CONSTRAINT reportes_vehiculo_id_fkey FOREIGN KEY (vehiculo_id) REFERENCES public.vehiculos(id)
);
CREATE TABLE public.zonas_operativas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  estado text NOT NULL,
  municipio text NOT NULL,
  parroquia text NOT NULL,
  sector text NOT NULL,
  CONSTRAINT zonas_operativas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.daily_activities_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  supervisor_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'DRAFT'::text,
  selected_activities ARRAY DEFAULT '{}'::text[],
  report_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT daily_activities_reports_pkey PRIMARY KEY (id),
  CONSTRAINT daily_activities_reports_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES auth.users(id)
);