INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'BELLA VISTA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'BRISAS DE ARAGUA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'BRISAS DE BUCARAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'CA�AOTE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'CAOBAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'CASCO CENTRAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'CIUDAD GUAYAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'COLINAS DE BUCARAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'CURIEPE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'EL BEISBOL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'EL LORO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'JABILLAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'JERUSALEN');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'LA CONCEPCION');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'LA GRUTA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'LAS LOMITAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'LOS LIMITES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'LOS PANAMERICANOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'SANTO DOMINGO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'TABACAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'TINAPUEY');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'TRAPICHE DEL MEDIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Aragua', 'Santos de Michelena', 'Las Tejerias', 'VARIANTES DE GUAYA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Distrito Capital', 'Libertador', 'Coche', 'COCHE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Distrito Capital', 'Libertador', 'El Valle', 'EL VALLE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Distrito Capital', 'Libertador', 'La Vega', 'LA VEGA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Distrito Capital', 'Libertador', 'Sucre (Catia)', 'PROPATRIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'BAROLA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'BARRIO BOLIVAR');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'BRISAS DE ORIENTE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'C.C COLISEO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'C.C DON PEDRO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'C.C LA CASCADA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'C.C TIBISAY');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'CASCO CENTRAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'CORRALITO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'FRANCISCO DE MIRANDA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'JOSE MANUEL ALVAREZ');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'LLANO ALTO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'LOMAS DE URQUIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'MONTA�A ALTA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'POTRERO DEL MEDIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'RES. ALTA VISTA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'RES. LOS EUCALIPTOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'SANTA EDUVIGES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Carrizal', 'Carrizal', 'YERBA BUENA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'AGUA FRIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'CACHAPAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'CANTARRANA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'CASCO CENTRAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'COCOROTE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'CORTADA DEL GUAYABO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL AGUACATAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL CALVARIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL GUAMAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL INGENIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL LIMON');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL NARANJAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL PE�ON');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'EL PRADO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'GUAICOCO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'GUAREGUARE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'LA CRUCESITA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'LA CULEBRILLA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'LA OCI');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'LOS AMISTOSOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'LOS COLORADOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'SAN JOSE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'SAN RAFAEL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Cecilio Acosta', 'VISTA HERMOSA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', '23 DE ENERO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'ALBERTO RAVELL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'ALTO VERDE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'AQUILES NAZOA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'BARRIO LA CRUZ');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'BARRIO MIRANDA I');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'BARRIO MIRANDA II');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'BARRIO VENEZUELA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'BRISAS DE PALO ALTO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'BUENOS AIRES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'C.C ALI PRIMERA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'C.C. VASCONIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'CARRETERA VIEJA CARACAS LOS TEQUES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'CENTRO LOS TEQUES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'CLUB HIPICO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'COLINAS DEL ANGEL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'COLINAS DEL PASO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'COOPERATIVA GUAICAIPURO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'CUMBRE ROJAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL AYACUCHO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL BARBECHO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL BOSQUE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL CABOTAJE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL ENCANTO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL NACIONAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL PANADERO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL PASO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL PUEBLO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL PUINKY');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL RETEN');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL RINCON');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL TAMBOR');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL TRABUCO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL TRIGO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'EL VIGIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'GUAREMAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'HOSPITAL VICTORINO SANTAELLA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'JOSE GREGORIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LA ESTRELLA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LA FONTANERA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LA MATICA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LA QUINTA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LAGUNETICA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LAS CADENAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LOS ALPES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LOS AMARILLOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LOS BARRIALES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LOS CERRITOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LOS LAGOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'LOS MANGOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'MACARENA SUR');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'MAL PASO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'MANUELA SAENZ');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'PALO ALTO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'PUNTA BRAVA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'QUEBRADA LA VIRGEN');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RAMO VERDE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. ALDEBARAN');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. CARACAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. EL CHORRITO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. ESCORPIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. IMOLA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. KNOOP');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. LA CIMA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. LAGUNETICA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. MIRACIELOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. MIRAFLORES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. PARQUE LAS AMERICAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. RIO ARRIBA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. SANTA MARIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. TAMARI');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. TINANTONIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. TIUNA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. TRIGO DORADO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RES. YATI');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'RETAMAL');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'ROMULO GALLEGOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'SAN OMERO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'SANTA EDUVIGES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'SANTA EULALIA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'SANTA ROSA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'SOLAR DE LA QUINTA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'URB. SIMON BOLIVAR');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'VALLE ALTO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'Los Teques', 'ZONA INDUSTRIAL EL TAMBOR');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'BOSQUE DE PINOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'EL PUEBLO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'POZO DE ROSAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Guaicaipuro', 'San Pedro de los Altos', 'SAN PEDRO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'AGUA LINDA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'ARBOLEDA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'BOSQUE ALEGRE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'C.C GALERIA LAS AMERICAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'C.C LA COLINA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'C.C. CEPAN');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'C.C. CLUB DE CAMPO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'C.C. DON BLAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'C.C. LA CASONA 2');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'EL AMARILLO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'EL PARAMO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'EL PUEBLO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'CLUB DE CAMPO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'EL RETIRO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'EL SITIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'KM 18');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'KM 8');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LA GONZALERA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LA GUADALUPE');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LA MORITA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LA OVEJA NEGRA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LA ROSALEDA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LAS CUMBRES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LAS MINAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LAS POLONIAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LOS CASTORES');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LOS HELECHOS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'LOS LLANEROS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'RES. EL ROCIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'RES. LAS CHURUATAS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'RES. OPS');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'RES. SAN ANTONIO');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'SIERRA BRAVA');
INSERT INTO public.zonas_operativas (estado, municipio, parroquia, sector) VALUES ('Miranda', 'Los salias', 'San antonio de los altos', 'ZONA INDUSTRIAL LAS MINAS');